name: 'pii'

config-version: 2
version: '0.1'

profile: 'pii'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

macro-paths: ["macros"]

models:
  pii:
    bronze:
      schema: bronze
      materialized: table
      +tags: 'bronze'
      +docs:
        node_color: '#cd7f32'

    silver:
      schema: silver
      materialized: table
      +tags: 'silver'
      +docs:
        node_color: 'silver'

    golden:
      schema: golden
      materialized: table
      +tags: 'golden'
      +docs:
        node_color: 'gold'