pii:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: 'pii.duckdb'
      threads: 3

    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'pii.duckdb') }}"
      threads: 25
      extensions:
        - postgres
      attach:
        - path: "{{ env_var('DBT_PG_CONN', 'postgresql://airflow:airflow@localhost:5432/airflow') }}"
          type: postgres
          alias: pg_db