pii:
  target: prod
  outputs:
    dev:
      type: duckdb
      path: 'pii.duckdb'
      threads: 3

    prod:
      type: postgres
      threads: 25
      extensions:
        - postgres
      attach:
        - path: "postgresql://pstgrs_user:pstgrs_pswd@pstgrs:9998/postgres"
          type: postgres
          alias: pg_db