pii:

  outputs:
    dev:
      type: duckdb
      path: 'pii.duckdb'
      threads: 3

    prod:
      type: postgres
      threads: 25
      extensions:
        - postgres
      attach:
        - path: "postgresql://airflow:airflow@postgres:9998/airflow"
          type: postgres
          alias: pg_db

  target: prod