pii:
  target: prod
  outputs:
    dev:
      type: duckdb
      path: 'pii.duckdb'
      threads: 3

    prod:
      type: duckdb
      threads: 25
      extensions:
        - postgres
      attach:
        - path: "postgresql://airflow:airflow@localhost:9998/airflow"
          type: postgres
          alias: pg_db
