name: 'scd_2'

config-version: 2
version: '0.1'

profile: 'scd_2'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  scd_2:

    bronze:
      schema: bronze
      materialized: table
      +tags: 'bronze'
      +docs:
        node_color: '#cd7f32'