name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

macro-paths: ["macros"]

models:
  jaffle_shop:

    bronze:
      schema: bronze
      materialized: table
      +tags: 'bronze'
      +docs:
        node_color: '#cd7f32'

    silver:
      schema: silver
      materialized: ephemeral
      +tags: 'silver'
      +docs:
        node_color: 'silver'

    golden:
      database: "{{ target.database if target.name == 'dev' else 'pg_db' }}"
      schema: gold
      materialized: table
      +tags: 'golden'
      +docs:
        node_color: 'gold'

