pii:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'pii.duckdb'
      threads: 3

    prod:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      dbname: airflow
      schema: driven
      port: 5432
